title: LukeeSec-Blog
description: "Hack The Box Writeups"
author:
  name: "LukeeSec"
  email: "lukemartin1968@yahoo.com"
  url: "https://lukeesec.github.io/s://ashishchaudhary.in/hacker-blog"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "LukeeSec"
year : "2019"
